---
title: 'Tidymodels #4: Hypothesis testing using resampling and tidy data'
author: "Jacob Lowell"
date: "4/23/2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE , message = FALSE , warning =  FALSE)

library(knitr)
options(digits=3)

library(gt)

```

I am working through the first post on the tidymodels site, located at : https://www.tidymodels.org/learn/statistics/infer/

# Section 1

## Generate data

```{r}
library(tidymodels) # Includes the infer package

# load in the data set
data(gss)

# take a look at its structure
dplyr::glimpse(gss)
```


```{r}
gss %>%
  specify(response = age) %>%
  class()
```


```{r}
gss %>%
  specify(age ~ partyid)

gss %>%
  specify(response = age, explanatory = partyid)
```

```{r}
gss %>%
  specify(response = college, success = "degree")
```


```{r}
gss %>%
  specify(college ~ partyid, success = "degree") %>%
  hypothesize(null = "independence")
```


### say the mean hypothesis is 40 hours per week

```{r}
gss %>%
  specify(response = hours) %>%
  hypothesize(null = "point", mu = 40)
```


```{r}
gss %>%
  specify(response = hours) %>%
  hypothesize(null = "point", mu = 40) %>%
  generate(reps = 5000, type = "bootstrap") 
```


```{r}
gss %>%
  specify(partyid ~ age) %>%
  hypothesize(null = "independence") %>%
  generate(reps = 5000, type = "permute")
```


```{r}
gss %>%
  specify(response = hours) %>%
  hypothesize(null = "point", mu = 40) %>%
  generate(reps = 5000, type = "bootstrap") %>%
  calculate(stat = "mean")
```


```{r}
gss %>%
  specify(age ~ college) %>%
  hypothesize(null = "independence") %>%
  generate(reps = 5000, type = "permute") %>%
  calculate("diff in means", order = c("degree", "no degree"))
```


```{r}
point_estimate <- gss %>%
  specify(response = hours) %>%
  calculate(stat = "mean")
#> Warning: Removed 1244 rows containing missing values.

# generate a null distribution
null_dist <- gss %>%
  specify(response = hours) %>%
  hypothesize(null = "point", mu = 40) %>%
  generate(reps = 5000, type = "bootstrap") %>%
  calculate(stat = "mean")
```


```{r}
null_dist %>%
  visualize()
```


```{r}
null_dist %>%
  visualize() +
  shade_p_value(obs_stat = point_estimate, direction = "two_sided")
```


```{r}
# get a two-tailed p-value
p_value <- null_dist %>%
  get_p_value(obs_stat = point_estimate, direction = "two_sided")

p_value
```




```{r}
null_dist %>%
  # calculate the confidence interval around the point estimate
  get_confidence_interval(point_estimate = point_estimate,
                          # at the 95% confidence level
                          level = .95,
                          # using the standard error
                          type = "se")
```




#  Theoretical methods

```{r}
null_f_distn <- gss %>%
   specify(age ~ partyid) %>%
   hypothesize(null = "independence") %>%
   generate(reps = 5000, type = "permute") %>%
   calculate(stat = "F")
```





```{r}
null_f_distn_theoretical <- gss %>%
   specify(age ~ partyid) %>%
   hypothesize(null = "independence") %>%
   calculate(stat = "F")


F_hat <- gss %>% 
  specify(age ~ partyid) %>%
  calculate(stat = "F")


visualize(null_f_distn_theoretical, method = "theoretical") +
  shade_p_value(obs_stat = F_hat, direction = "greater")
```



```{r}
visualize(null_f_distn, method = "both") +
  shade_p_value(obs_stat = F_hat, direction = "greater")
```

